package com.szhynet.lib.mpermission;

import java.util.HashMap;
import java.util.Map;

import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;

public class ProxyInfo
{
    private String packageName;
    private String proxyClassName;
    private TypeElement typeElement;

    Map<int[], String> grantMethodMap = new HashMap<>();
    Map<int[], String> deniedMethodMap = new HashMap<>();
    Map<int[], String> rationaleMethodMap = new HashMap<>();

    public static final String PROXY = "PermissionProxy";

    public ProxyInfo(Elements elementUtils, TypeElement classElement)
    {
        PackageElement packageElement = elementUtils.getPackageOf(classElement);
        String packageName = packageElement.getQualifiedName().toString();
        //classname
        String className = ClassValidator.getClassName(classElement, packageName);
        this.packageName = packageName;
        this.proxyClassName = className + "$$" + PROXY;
    }


    public String getProxyClassFullName()
    {
        return packageName + "." + proxyClassName;
    }

    public String generateJavaCode()
    {
        StringBuilder builder = new StringBuilder();
        builder.append("//===============================================================//");
        builder.append("// Sxxjava:\n// This file is automatically generated by the compiler, please do not change manually;!" +
                "\n// Sxxjava:\n// 本文件的代码是由编译器自动生成的,请勿手动更改!\n");
        builder.append("//===============================================================//\n\n");
        builder.append("package ").append(packageName).append(";\n\n");
        builder.append("import com.szhynet.lib.mpermission.*;\n");
        builder.append('\n');

        builder.append("public class ").append(proxyClassName).append(" implements " + ProxyInfo.PROXY + "<" + typeElement.getSimpleName() + ">");
        builder.append(" {\n");

        generateMethods(builder);
        builder.append('\n');

        builder.append("}\n");
        return builder.toString();

    }


    private void generateMethods(StringBuilder builder)
    {
        generateGrantMethod(builder);
        generateDeniedMethod(builder);
        generateRationaleMethod(builder);
    }

    private void generateRationaleMethod(StringBuilder builder)
    {
        builder.append("@Override\n ");
        builder.append("public void rationale(" + typeElement.getSimpleName() + " source , int requestCode) {\n");
        builder.append("switch(requestCode) {");
        for (int[] codes : rationaleMethodMap.keySet())
        {
            for (int code : codes){
                builder.append("case " + code + ":");
                builder.append("source." + rationaleMethodMap.get(codes) + "(" + code + ");");
                builder.append("break;");
            }
        }

        builder.append("}");
        builder.append("  }\n");

        ///

        builder.append("@Override\n ");
        builder.append("public boolean needShowRationale(int requestCode) {\n");
        builder.append("switch(requestCode) {");
        for (int[] codes : rationaleMethodMap.keySet())
        {
            for (int code : codes){
                builder.append("case " + code + ":");
            }
            builder.append("return true;");
        }
        builder.append("}\n");
        builder.append("return false;");

        builder.append("  }\n");
    }

    private void generateDeniedMethod(StringBuilder builder)
    {
        builder.append("@Override\n ");
        builder.append("public void denied(" + typeElement.getSimpleName() + " source , int requestCode) {\n");
        builder.append("switch(requestCode) {");
        for (int[] codes : deniedMethodMap.keySet())
        {
            for (int code : codes){
                builder.append("case " + code + ":");
                builder.append("source." + deniedMethodMap.get(codes) + "("+code+");");
                builder.append("break;");
            }
        }

        builder.append("}");
        builder.append("  }\n");
    }

    private void generateGrantMethod(StringBuilder builder)
    {
        builder.append("@Override\n ");
        builder.append("public void grant(" + typeElement.getSimpleName() + " source , int requestCode) {\n");
        builder.append("switch(requestCode) {");
        for (int[] codes : grantMethodMap.keySet())
        {
            for (int code : codes){
                builder.append("case " + code + ":");
                builder.append("source." + grantMethodMap.get(codes) + "("+code+");");
                builder.append("break;");
            }
        }

        builder.append("}");
        builder.append("  }\n");
    }

    public TypeElement getTypeElement()
    {
        return typeElement;
    }

    public void setTypeElement(TypeElement typeElement)
    {
        this.typeElement = typeElement;
    }


}